# Generated by Django 2.1.2 on 2019-05-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0022_auto_20190505_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('EID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Location', models.CharField(max_length=50)),
                ('Registration_Link', models.URLField(blank=True, null=True)),
                ('GID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.group')),
            ],
        ),
    ]
