# Generated by Django 2.1.2 on 2019-04-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='society',
            fields=[
                ('CID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Established', models.DateTimeField()),
                ('Current_Member_Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='society_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=30)),
                ('Member_Since', models.DateField()),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.society')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=50)),
                ('DOB', models.DateField()),
                ('Branch', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Contact', models.BigIntegerField(null=True)),
                ('Password', models.CharField(max_length=12)),
                ('Last_Login', models.DateTimeField()),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='society_members',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.student'),
        ),
    ]
