# Generated by Django 2.1.2 on 2019-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_Login',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('Student', 'Student'), ('EB', ()), ('CR', (('1', 'Aerospace'), ('2', 'Civil'), ('3', 'Computer Science'), ('4', 'Electronics & Communication'), ('5', 'Electrical'), ('6', 'Mechanical'), ('7', 'Materials & Metallurgical'), ('8', 'Production & Industrial')))], default='Student', max_length=20),
        ),
    ]
