# Generated by Django 2.1.2 on 2019-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20190418_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('Student', 'Student'), ('CR', (('1', 'Aerospace'), ('2', 'Civil'), ('3', 'Computer Science'), ('4', 'Electronics & Communication'), ('5', 'Electrical'), ('6', 'Mechanical'), ('7', 'Materials & Metallurgical'), ('8', 'Production & Industrial')))], default='Student', max_length=20),
        ),
    ]
