# Generated by Django 2.1.2 on 2019-04-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20190418_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(choices=[('Student', 'Student'), ('CR', 'Class Representative')], default='Student', max_length=20),
        ),
    ]
