# Generated by Django 2.1.2 on 2019-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20190418_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Last_Login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
