# Generated by Django 2.1.2 on 2019-04-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20190418_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Branch',
        ),
    ]
