# Generated by Django 2.1.2 on 2019-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_auto_20190426_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
