# Generated by Django 2.1.2 on 2019-05-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Picture',
        ),
    ]
