# Generated by Django 2.1.2 on 2019-05-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0010_auto_20190505_1046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='society_members',
            new_name='group_members',
        ),
    ]
