# Generated by Django 2.1.2 on 2019-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0011_auto_20190505_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Is_Club',
            field=models.BooleanField(default=True),
        ),
    ]
