# Generated by Django 2.1.2 on 2019-05-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0012_group_is_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Role',
        ),
    ]
