# Generated by Django 2.1.2 on 2019-05-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0013_remove_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Is_CR',
            field=models.BooleanField(default=False),
        ),
    ]
