# Generated by Django 2.1.2 on 2019-05-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0014_student_is_cr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_members',
            old_name='CID',
            new_name='GID',
        ),
    ]
