# Generated by Django 2.1.2 on 2019-05-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0015_auto_20190505_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_members',
            name='Role',
        ),
    ]
