# Generated by Django 2.1.2 on 2019-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0016_remove_group_members_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_members',
            name='Is_EB',
            field=models.BooleanField(default=False),
        ),
    ]
