# Generated by Django 2.1.2 on 2019-05-05 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('acc', '0017_group_members_is_eb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='CID',
            new_name='GID',
        ),
        migrations.AlterField(
            model_name='group_members',
            name='GID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.group', to_field='CID'),
        ),
    ]
