# Generated by Django 2.1.2 on 2019-05-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0018_auto_20190505_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_members',
            name='GID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.group'),
        ),
    ]
