# Generated by Django 2.1.2 on 2019-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0020_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
