# Generated by Django 2.1.2 on 2019-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0021_auto_20190505_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Picture',
            field=models.ImageField(upload_to='dp/'),
        ),
    ]
