# Generated by Django 2.1.2 on 2019-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='CID',
            new_name='Club_ID',
        ),
        migrations.AddField(
            model_name='poll',
            name='Subject',
            field=models.TextField(null=True),
        ),
    ]
