# Generated by Django 2.1.2 on 2019-05-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='Club_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.society'),
        ),
    ]
