# Generated by Django 2.1.2 on 2019-05-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0004_auto_20190505_1008'),
        ('pll', '0002_auto_20190429_0717'),
    ]

    operations = [
    ]
