# Generated by Django 2.1.2 on 2019-05-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0005_merge_20190505_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='Club_ID',
            new_name='GID',
        ),
    ]
