# Generated by Django 2.1.2 on 2019-05-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0008_auto_20190505_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='CR_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.student'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='GID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.group'),
        ),
    ]
