# Generated by Django 2.1.2 on 2019-04-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('AID', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.TextField()),
                ('Timestamp', models.DateTimeField()),
                ('Content', models.TextField()),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.society')),
                ('CR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.student')),
            ],
        ),
    ]
