# Generated by Django 2.1.2 on 2019-05-05 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0003_auto_20190505_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='CID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.group', to_field='CID'),
        ),
    ]
