# Generated by Django 2.1.2 on 2019-05-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0008_auto_20190505_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='AID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
