# Generated by Django 2.1.2 on 2019-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0009_auto_20190507_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
