# Generated by Django 2.1.2 on 2019-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ann', '0010_auto_20190507_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
