# Generated by Django 2.1.2 on 2019-04-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('Answer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Answer', models.TextField()),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query_ID', models.IntegerField()),
                ('Asker_ID', models.IntegerField()),
                ('Content', models.TextField()),
                ('Timestamp', models.DateTimeField()),
                ('Category', models.TextField()),
                ('Year', models.IntegerField()),
                ('Branch', models.TextField()),
                ('Society_ID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='QID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques.query'),
        ),
        migrations.AddField(
            model_name='answer',
            name='Respondent_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.student'),
        ),
    ]
