# Generated by Django 2.1.2 on 2019-04-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Category',
        ),
        migrations.AddField(
            model_name='query',
            name='Subject',
            field=models.TextField(default='Data Structures'),
        ),
    ]
