# Generated by Django 2.1.2 on 2019-05-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0003_auto_20190503_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Asker_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.student'),
        ),
    ]
