# Generated by Django 2.1.2 on 2019-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0006_auto_20190507_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Query_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
