# Generated by Django 2.1.2 on 2019-05-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0007_auto_20190507_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Respondent_ID',
            new_name='Respondent',
        ),
    ]
