# Generated by Django 2.1.2 on 2019-04-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('MID', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('Timestamp', models.DateTimeField()),
                ('Reciever_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r', to='acc.student')),
                ('Sender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='acc.student')),
            ],
        ),
    ]
