# Generated by Django 2.1.2 on 2019-04-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('RID', models.IntegerField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Category', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=50)),
                ('Location', models.FileField(upload_to='')),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.society')),
                ('CR_SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.student')),
            ],
        ),
    ]
