# Generated by Django 2.1.2 on 2019-05-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20190507_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='Location',
            new_name='File',
        ),
    ]
