# Generated by Django 2.1.2 on 2019-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20190507_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
