# Generated by Django 2.1.2 on 2019-05-07 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_resource_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='subjects'),
            preserve_default=False,
        ),
    ]
