# Generated by Django 2.1.2 on 2019-05-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_subject_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='RID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
