# Generated by Django 2.1.2 on 2019-05-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20190507_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='File',
            field=models.FileField(upload_to='files/'),
        ),
    ]
