# Generated by Django 2.1.2 on 2019-05-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20190507_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='Uploader_ID',
            new_name='Uploader',
        ),
    ]
