# Generated by Django 2.1.2 on 2019-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20190507_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Details',
            field=models.TextField(default='File'),
        ),
    ]
